# Generated by Django 5.0.2 on 2024-02-27 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "display_name",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("date_joined", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("avatar_base64", models.TextField(blank=True, default="")),
                ("friends", models.CharField(default="", max_length=1000)),
                ("nb_wins", models.IntegerField(default=0)),
                ("nb_losses", models.IntegerField(default=0)),
                ("nb_plays", models.IntegerField(default=0)),
                ("status", models.CharField(default="offline", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_42_user", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_player_score", models.IntegerField()),
                ("second_player_score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results_as_first_player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "second_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results_as_second_player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
