# Generated by Django 5.0.2 on 2024-02-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_avatar_base64"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="avatar_base64",
            new_name="avatar",
        ),
    ]
