# Generated by Django 5.0.2 on 2024-03-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_access_token_customuser_otp_base32_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="status_2fa",
            new_name="otp_enabled",
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_auth_url",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
