# Generated by Django 5.0.2 on 2024-03-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_status_2fa_customuser_otp_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
