# Generated by Django 5.0.2 on 2024-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
