# Generated by Django 5.0.2 on 2024-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="access_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
