# Generated by Django 5.0.2 on 2024-03-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_access_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="access_token",
        ),
    ]
