export default {
	titles: {
		"404": "404 Non trouvé | Pong",
		"/": "Accueil | Pong",
		"/sign_in": "Se connecter | Pong",
		"/sign_up": "S'inscrire | Pong",
		"/game": "Jeu | Pong",
		"/profile": "Profil | Pong",
		"/friends": "Amis | Pong",
		"/game_b": "Mode de jeu | Pong",
		"/go_pwd": "Changer mot de passe | Pong",
		"/history": "Historique | Pong",
		"/settings": "Paramètres | Pong",
		"/tournement": "Tournoi | Pong",
	},

	placeholders: {
		"username": "Nom",
		"password": "Mot de passe",
		"his_username" : "Son nom d'utilisateur",
		"old_ph": "Ancien mot de passe",
		"new_ph": "Nouveau mot de passe",
		"dis_nh": "Nom d'affichage",
		"dis_unh": "Nom d'utilisateur",
		"p2_placeho": "Nom du joueur 2",
		"p1": "Joueur 1",
		"p2": "Joueur 2",
		"p3": "Joueur 3",
		"p4": "Joueur 4",
	},

	not_found: "Page non trouvée",
	start_now: "Commencer",
	signin: "Se connecter",
	signin_intra: "Se connecter avec 42",
	text_signin: "Vous n'avez pas encore de compte?",
	click: "Cliquez ici",
	or: "Ou",
	signup: "S'inscrire",
	text_signup: "Vous avez déjà un compte?",
	usr_up: "Doit être unique",
	pwd_up: "Mot de passe non sécurisé",
	usr_in: "Utilisateur non trouvé",
	pwd_in: "Mot de passe incorrect",
	wins: "Victoires: ",
	losses: "Défaites: ",
	add_fr: "Ajouter des amis",
	fr_name: "Nom d'utilisateur:",
	add: "Ajouter",
	fr_list: "Liste d'amis",
	vs: "1 vS 1",
	tour: "Tournoi",
	upd_p: "Mettre à jour le mot de passe",
	old_p: "Ancien mot de passe:",
	new_p: "Nouveau mot de passe:",
	change: "Changer",
	date: "Date",
	won: "Gagné",
	lost: "Perdu",
	st: "Paramètres",
	dis_n: "Nom d'affichage:",
	dis_un: "Nom d'utilisateur:",
	up_inf: "Mettre à jour ",
	chng: "Changer le mot de passe",
	chng_av: "Changer l'avatar",
	nav_home: "Accueil",
	nav_game: "Jeu",
	nav_his: "Historique",
	nav_fr: "Amis",
	nav_st: "Paramètres",
	nav_logout: "Se déconnecter",
	fri1: "Tu ne peux pas t'ajouter toi-même",
	fri2: "Ami existe déjà",
	fri3: "Ami ajouté avec succès",
	fri4: "Ami non trouvé",
	old_p_err: "Ancien mot de passe incorrect",
	new_p_err: "Nouveau mot de passe non sécurisé",
	av_err: "Opération échouée",
	empty: "Aucun fichier ajouté",
	display_name: "Doit être unique",
	username: "Déjà utilisé",
	avva: "Changer l'avatar",
	change_a: "Changer",
	on: "en ligne",
	off: "hors ligne",

	ptwo: "choisissez un joueur 2",
	start_: "Commencer le jeu",
	tr_name: "Choisissez les noms du tournoi",
};
