export default {
	titles: {
		"404": "404 Not Found | Pong",
        "/": "Home | Pong",
		"/sign_in": "Sign In | Pong",
		"/sign_up": "Sign Up | Pong",
		"/game": "Game | Pong",
		"/profile": "Profile | Pong",
		"/friends": "Friends | Pong",
		"/game_b": "Game mode | Pong",
		"/go_pwd": "Change password | Pong",
		"/history": "History | Pong",
		"/settings": "Settings | Pong",
    },

	placeholders: {
		"username": "Username",
		"password": "Password",
		"his_username" : "His username",
		"old_ph": "Old password",
		"new_ph": "New password",
		"dis_nh": "Display name",
		"dis_unh": "Username",
	},
	
	not_found: "Page not found",
	start_now: "Start Now",
	signin: "Sign In",
	signin_intra: "Sign with 42",
	text_signin: "You don't have an account yet?",
	click: "Click here",
	or: "Or",
	signup: "Sign Up",
	text_signup: "You already have an account?",
	usr_up: "Must be unique",
	pwd_up: "At least 8 characters",
	usr_in: "User not found",
	pwd_in: "Incorrect password",
	wins: "Wins: ",
	losses: "Losses: ",
	add_fr: "Add friends",
	fr_name: "Username:",
	add: "Add",
	fr_list: "Friends list",
	vs: "1 vS 1",
	tour: "Tournament",
	upd_p: "Update password",
	old_p: "Old password:",
	new_p: "New password:",
	change: "Change",
	date: "Date",
	won: "Won",
	lost: "Lost",

	st: "Settings",
	dis_n: "Display name:",
	dis_un: "Username:",
	up_inf: "Update information",
	chng: "Change Password",
	chng_av: "Change Avatar",
};
