export default {
	titles: {
		"404": "404 Not Found | Pong",
        "/": "Home | Pong",
		"/sign_in": "Sign In | Pong",
		"/sign_up": "Sign Up | Pong",
		"/game": "Game | Pong",
		"/profile": "Profile | Pong",
		"/friends": "Friends | Pong",
		"/game_b": "Game mode | Pong",
		"/go_pwd": "Change password | Pong",
		"/history": "History | Pong",
		"/settings": "Settings | Pong",
    },

	placeholders: {
		"username": "Username",
		"password": "Password",
		"his_username" : "His username",
		"old_ph": "Old password",
		"new_ph": "New password",
		"dis_nh": "Display name",
		"dis_unh": "Username",
	},
	
	not_found: "Page not found",
	start_now: "Start Now",
	signin: "Sign In",
	signin_intra: "Sign with 42",
	text_signin: "You don't have an account yet?",
	click: "Click here",
	or: "Or",
	signup: "Sign Up",
	text_signup: "You already have an account?",
	usr_up: "Must be unique",
	pwd_up: "Password not secured",
	usr_in: "User not found",
	pwd_in: "Incorrect password",
	wins: "Wins: ",
	losses: "Losses: ",
	add_fr: "Add friends",
	fr_name: "Username:",
	add: "Add",
	fr_list: "Friends list",
	vs: "1 vS 1",
	tour: "Tournament",
	upd_p: "Update password",
	old_p: "Old password:",
	new_p: "New password:",
	change: "Change",
	date: "Date",
	won: "Won",
	lost: "Lost",
	st: "Settings",
	dis_n: "Display name:",
	dis_un: "Username:",
	up_inf: "Update information",
	chng: "Change Password",
	chng_av: "Change Avatar",
	nav_home: "Home",
	nav_game: "Game",
	nav_his: "History",
	nav_fr: "Friends",
	nav_st: "Settings",
	nav_logout: "Log out",
	fri1: "You cannot send a friend request to yourself",
	fri2: "Friend already exists",
	fri3: "Friend added successfully",
	fri4: "User not found",
	old_p_err: "Old password is incorrect",
	new_p_err: "New password not secured",
	av_err: "Avatar upload failed",
	empty: "No file added",
	display_name: "Display name must be unique",
	username: "Username must be unique",
	avva: "Change Avatar",
	change_a: "Change",
	
	on: "Online",
	off: "Offline",
};
