# Generated by Django 5.0.2 on 2024-02-20 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_rename_is_admin_user_is_42_user_user_status_games"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="losses",
            new_name="nb_losses",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="plays",
            new_name="nb_plays",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="wins",
            new_name="nb_wins",
        ),
    ]
