# Generated by Django 5.0.2 on 2024-02-24 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_rename_losses_user_nb_losses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
