# Generated by Django 5.0.2 on 2024-02-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_remove_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
