# Generated by Django 5.0.2 on 2024-02-12 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                (
                    "display_name",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("date_joined", models.DateTimeField(auto_now=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("avatar_base64", models.TextField(blank=True, default="")),
                ("friends", models.CharField(default="", max_length=1000)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("plays", models.IntegerField(default=0)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
