# Generated by Django 5.0.2 on 2024-02-18 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_42_user",
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="offline", max_length=100),
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_player_score", models.IntegerField()),
                ("second_player_score", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results_as_first_player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "second_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results_as_second_player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
